version: "2"
services:
  php-env:
    image: ilife-image
    ports: 
      -3000:3000
    volumes:
      ./app:/var/www/html
  
  sql105.infinityfree.com:
    image: phpmyadmin:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: if0_36143180
      MYSQL_ROOT_PASSWORD: Shova595

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 3001:3000
    environment:
      - PMA_ARBITRARY=1